- name: variables from files
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: please enter course name
    private: fales # it is not confidential information
  - name: DURATION
    prompt: please enter duration
    private: fales
  - name: TRAINER
    prompt: please enter trainer name 
  tasks: 
  - name: print course infromation
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, duration is {{ DURATION }}, trainer is {{ TRAINER }}"

